import React from "react";
import Head from "next/head";
import Link from "next/link";

export const metadata = {
  title: "The Movies APP",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: React.ReactNode;
}

const Layout = ({ children }: LayoutProps) => {
  return (
    <>
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <nav className="flex justify-between items-center bg-gray-800 text-white p-4">
        <div className="text-xl font-bold">
          <Link href="/">
            <span>The Movies APP</span>
          </Link>
        </div>
        <div className="relative">
          <button className="flex items-center">
            Opciones
            <svg
              className="ml-2 w-5 h-5"
              viewBox="0 0 20 20"
              fill="currentColor"
            >
              <path
                fillRule="evenodd"
                d="M6 6l8 4-8 4V6zm1 4v2h4v-2H7z"
                clipRule="evenodd"
              />
            </svg>
          </button>
          <div className="absolute right-0 mt-2 bg-white text-gray-800 border rounded-md shadow-lg hidden">
            <ul className="py-2 px-4">
              <li className="cursor-pointer hover:bg-gray-200 py-1">
                Upcoming
              </li>
              <li className="cursor-pointer hover:bg-gray-200 py-1">Popular</li>
              <li className="cursor-pointer hover:bg-gray-200 py-1">
                Top rated
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <main>{children}</main>
    </>
  );
};

export default Layout;
