import React from "react";
import Link from "next/link";
import Head from "next/head";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <body className="bg-black">
        <nav className="flex justify-between items-center text-white p-4 px-20 bg-gray-800">
          <div className="text-xl font-bold">
            <Link href="/" passHref>
              <span>The Movies APP</span>
            </Link>
          </div>
          <div
            className="text-xl font-bold inline-block"
            style={{ display: "inline-block" }}
          >
            <div className="flex">
              <Link href="/upcoming" passHref>
                <p className="text-sm hover:font-bold mr-10">Upcoming</p>
              </Link>
              <Link href="/" passHref>
                <p className="text-sm hover:font-bold mr-10">Popular</p>
              </Link>
              <Link href="/top_rated" passHref>
                <p className="text-sm hover:font-bold">Top Rated</p>
              </Link>
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
