import React from "react";
import Head from "next/head";
import Link from "next/link";

export const metadata = {
  title: "The Movies APP",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: React.ReactNode;
}

const Layout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <>
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <nav className="flex justify-between items-center text-white p-4 px-20 bg-gray-800">
        <div className="text-xl font-bold">
          <Link href="/" passHref>
            <span>The Movies APP</span>
          </Link>
        </div>
        <div className="text-xl font-bold" style={{ display: "inline-block" }}>
          <Link href="/upcoming" passHref>
            <p
              className="text-sm hover:font-bold mr-10"
              style={{ display: "inline" }}
            >
              Upcoming
            </p>
          </Link>
          <Link href="/" passHref>
            <p
              className="text-sm hover:font-bold mr-10"
              style={{ display: "inline" }}
            >
              Popular
            </p>
          </Link>
          <Link href="/top_rated" passHref>
            <p
              className="text-sm hover:font-bold"
              style={{ display: "inline" }}
            >
              Top Rated
            </p>
          </Link>
        </div>
      </nav>
      <main className="bg-whithe">{children}</main>
    </>
  );
};

export default Layout;
